# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['sidebar_main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('icons', 'icons'),
        ('icon2', 'icon2'),
        ('images', 'images'),
    ],
    hiddenimports=[
        'win32com.client',
        'win32com.server',
        'win32gui',
        'win32con',
        'win32api',
        'win32timezone',
        'pythoncom',
        'pywintypes',
        'PIL',
        'PIL._tkinter_finder',
        'msal',
        'requests',
        'urllib3',
        'sentry_sdk',
        # --- All sidebar modules ---
        'sidebar',
        'sidebar.core',
        'sidebar.core.config',
        'sidebar.core.config_manager',
        'sidebar.core.theme',
        'sidebar.core.compat',
        'sidebar.core.appbar',
        'sidebar.services',
        'sidebar.services.outlook_client',
        'sidebar.services.update_checker',
        'sidebar.ui',
        'sidebar.ui.panels',
        'sidebar.ui.panels.settings',
        'sidebar.ui.panels.help',
        'sidebar.ui.panels.account_settings',
        'sidebar.ui.dialogs',
        'sidebar.ui.dialogs.feedback',
        'sidebar.ui.dialogs.share',
        'sidebar.ui.widgets',
        'sidebar.ui.widgets.base',
        'sidebar.ui.widgets.toolbar',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='InboxBar',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['icons\\inboxbar.ico'],
    version='file_version_info.txt',
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='InboxBar',
)
